
numero1 = 5
numero2 = 0

try: 
    result = numero1 / numero2
except Exception:
    print("se ha producido un error")
    
    
    
print("final exitoso")